### ISSUE TITLE
Train Help

### ISSUE THREAD

**Issue by kbrajwani** [lavis-nlp/jerex#9]
I have tried to  create data by devide text into sentance from spacy and mannually anotate. After that i am trying to train the model and i am getting following error. Can you please help me here?
As per me the main error is my sentence length. So is their any limit of that?

Epoch 0:   0% 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./jerex_train.py", line 20, in train
    model.train(cfg)
  File "/content/jerex/jerex/model.py", line 341, in train
    trainer.fit(model, datamodule=data_module)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/training_loop.py", line 492, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/training_loop.py", line 654, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/training_loop.py", line 433, in optimizer_step
    using_lbfgs=is_lbfgs,
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/lightning.py", line 1390, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/optimizer.py", line 214, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/optimizer.py", line 134, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 277, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 282, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 163, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/optimization.py", line 318, in step
    loss = closure()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/training_loop.py", line 649, in train_step_and_backward_closure
    split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/training_loop.py", line 742, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/training_loop.py", line 293, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 156, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 125, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "/content/jerex/jerex/model.py", line 114, in training_step
    outputs = self(**batch)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/jerex/jerex/model.py", line 106, in forward
    max_rel_pairs=max_rel_pairs, inference=inference)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/jerex/jerex/models/joint_models.py", line 142, in forward
    return self._forward_train(*args, **kwargs)
  File "/content/jerex/jerex/models/joint_models.py", line 188, in _forward_train
    max_spans=max_spans)
  File "/content/jerex/jerex/models/joint_models.py", line 57, in _forward_train_common
    h = self.bert(input_ids=encodings, attention_mask=context_masks)['last_hidden_state']
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py", line 969, in forward
    past_key_values_length=past_key_values_length,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py", line 207, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (1514) must match the size of tensor b (700) at non-singleton dimension 1

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by markus-eberts** [comment]
Hi,
you can increase the number of position embedding by the configuration setting 'model.position_embeddings_count' - just add it to your train.yaml. For other available configuration settings have a look at 'jerex/configs.py'.

**Comment by kbrajwani** [comment]
Hey, Thanks.
i have changed the model part of train.yaml file like this
model:
  model_type: joint_multi_instance
  encoder_path: bert-base-cased
  tokenizer_path: bert-base-cased
  mention_threshold: 0.85
  coref_threshold: 0.85
  rel_threshold: 0.6
  prop_drop: 0.1
  meta_embedding_size: 25
  size_embeddings_count: 30
  ed_embeddings_count: 300
  token_dist_embeddings_count: 1600
  sentence_dist_embeddings_count: 50
  position_embeddings_count: 1600

It's started the training but it's unexpectedly stop the process at the time of validation. My suspect is that it's out of ram.

```
datasets:
  train_path: ./data/datasets/docred_joint/train_joint.json
  valid_path: ./data/datasets/docred_joint/dev_joint.json
  test_path: null
  types_path: ./data/datasets/docred_joint/types.json
model:
  model_type: joint_multi_instance
  encoder_path: bert-base-cased
  tokenizer_path: bert-base-cased
  mention_threshold: 0.85
  coref_threshold: 0.85
  rel_threshold: 0.6
  prop_drop: 0.1
  meta_embedding_size: 25
  size_embeddings_count: 30
  ed_embeddings_count: 300
  token_dist_embeddings_count: 1600
  sentence_dist_embeddings_count: 50
  position_embeddings_count: 1600
sampling:
  neg_mention_count: 200
  neg_coref_count: 200
  neg_relation_count: 200
  max_span_size: 10
  sampling_processes: 8
  neg_mention_overlap_ratio: 0.5
  lowercase: false
loss:
  mention_weight: 1.0
  coref_weight: 1.0
  entity_weight: 0.25
  relation_weight: 1.0
inference:
  valid_batch_size: 1
  test_batch_size: 1
  max_spans: null
  max_coref_pairs: null
  max_rel_pairs: null
training:
  batch_size: 1
  min_epochs: 20
  max_epochs: 20
  lr: 5.0e-05
  lr_warmup: 0.1
  weight_decay: 0.01
  max_grad_norm: 1.0
  accumulate_grad_batches: 1
  max_spans: null
  max_coref_pairs: null
  max_rel_pairs: null
distribution:
  gpus: []
  accelerator: ''
  prepare_data_per_node: false
misc:
  store_predictions: true
  store_examples: true
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 1000
  deterministic: false
  seed: null
  cache_path: null
  precision: 32
  profiler: null
  final_valid_evaluate: true

[2021-08-20 11:40:29,685][filelock][INFO] - Lock 140040700798608 acquired on /root/.cache/huggingface/transformers/6508e60ab3c1200bffa26c95f4b58ac6b6d95fba4db1f195f632fa3cd7bc64cc.437aa611e89f6fc6675a049d2b5545390adbc617e7d655286421c191d2be2791.lock
Downloading: 100% 213k/213k [00:00<00:00, 1.18MB/s]
[2021-08-20 11:40:30,183][filelock][INFO] - Lock 140040700798608 released on /root/.cache/huggingface/transformers/6508e60ab3c1200bffa26c95f4b58ac6b6d95fba4db1f195f632fa3cd7bc64cc.437aa611e89f6fc6675a049d2b5545390adbc617e7d655286421c191d2be2791.lock
[2021-08-20 11:40:30,958][filelock][INFO] - Lock 140040664185872 acquired on /root/.cache/huggingface/transformers/ec84e86ee39bfe112543192cf981deebf7e6cbe8c91b8f7f8f63c9be44366158.ec5c189f89475aac7d8cbd243960a0655cfadc3d0474da8ff2ed0bf1699c2a5f.lock
Downloading: 100% 29.0/29.0 [00:00<00:00, 29.4kB/s]
[2021-08-20 11:40:31,220][filelock][INFO] - Lock 140040664185872 released on /root/.cache/huggingface/transformers/ec84e86ee39bfe112543192cf981deebf7e6cbe8c91b8f7f8f63c9be44366158.ec5c189f89475aac7d8cbd243960a0655cfadc3d0474da8ff2ed0bf1699c2a5f.lock
[2021-08-20 11:40:31,483][filelock][INFO] - Lock 140040663695184 acquired on /root/.cache/huggingface/transformers/226a307193a9f4344264cdc76a12988448a25345ba172f2c7421f3b6810fddad.3dab63143af66769bbb35e3811f75f7e16b2320e12b7935e216bd6159ce6d9a6.lock
Downloading: 100% 436k/436k [00:00<00:00, 1.41MB/s]
[2021-08-20 11:40:32,058][filelock][INFO] - Lock 140040663695184 released on /root/.cache/huggingface/transformers/226a307193a9f4344264cdc76a12988448a25345ba172f2c7421f3b6810fddad.3dab63143af66769bbb35e3811f75f7e16b2320e12b7935e216bd6159ce6d9a6.lock
Parse dataset '/content/jerex/data/datasets/docred_joint/train_joint.json': 100% 1/1 [00:00<00:00,  8.52it/s]
Parse dataset '/content/jerex/data/datasets/docred_joint/dev_joint.json': 100% 1/1 [00:00<00:00,  9.07it/s]
[2021-08-20 11:40:33,908][filelock][INFO] - Lock 140040643181776 acquired on /root/.cache/huggingface/transformers/a803e0468a8fe090683bdc453f4fac622804f49de86d7cecaee92365d4a0f829.a64a22196690e0e82ead56f388a3ef3a50de93335926ccfa20610217db589307.lock
Downloading: 100% 570/570 [00:00<00:00, 619kB/s]
[2021-08-20 11:40:34,168][filelock][INFO] - Lock 140040643181776 released on /root/.cache/huggingface/transformers/a803e0468a8fe090683bdc453f4fac622804f49de86d7cecaee92365d4a0f829.a64a22196690e0e82ead56f388a3ef3a50de93335926ccfa20610217db589307.lock
[2021-08-20 11:40:34,438][filelock][INFO] - Lock 140040647274000 acquired on /root/.cache/huggingface/transformers/092cc582560fc3833e556b3f833695c26343cb54b7e88cd02d40821462a74999.1f48cab6c959fc6c360d22bea39d06959e90f5b002e77e836d2da45464875cda.lock
Downloading: 100% 436M/436M [00:07<00:00, 62.0MB/s]
[2021-08-20 11:40:41,540][filelock][INFO] - Lock 140040647274000 released on /root/.cache/huggingface/transformers/092cc582560fc3833e556b3f833695c26343cb54b7e88cd02d40821462a74999.1f48cab6c959fc6c360d22bea39d06959e90f5b002e77e836d2da45464875cda.lock
Some weights of the model checkpoint at bert-base-cased were not used when initializing JointMultiInstanceModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'bert.pooler.dense.weight', 'bert.pooler.dense.bias']
- This IS expected if you are initializing JointMultiInstanceModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing JointMultiInstanceModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of JointMultiInstanceModel were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['mention_localization.linear.weight', 'mention_localization.linear.bias', 'mention_localization.mention_classifier.weight', 'mention_localization.mention_classifier.bias', 'mention_localization.size_embeddings.weight', 'coreference_resolution.coref_linear.weight', 'coreference_resolution.coref_linear.bias', 'coreference_resolution.coref_classifier.weight', 'coreference_resolution.coref_classifier.bias', 'coreference_resolution.coref_ed_embeddings.weight', 'entity_classification.linear.weight', 'entity_classification.linear.bias', 'entity_classification.entity_classifier.weight', 'entity_classification.entity_classifier.bias', 'relation_classification.pair_linear.weight', 'relation_classification.pair_linear.bias', 'relation_classification.rel_linear.weight', 'relation_classification.rel_linear.bias', 'relation_classification.rel_classifier.weight', 'relation_classification.rel_classifier.bias', 'relation_classification.token_distance_embeddings.weight', 'relation_classification.sentence_distance_embeddings.weight', 'relation_classification.entity_type_embeddings.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py:52: UserWarning: GPU available but not used. Set the --gpus flag when calling the script.
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))

  | Name  | Type                    | Params
--------------------------------------------------
0 | model | JointMultiInstanceModel | 114 M 
--------------------------------------------------
114 M     Trainable params
0         Non-trainable params
114 M     Total params
458.510   Total estimated model params size (MB)
Epoch 0: 100% 2/2 [00:22<00:00, 11.45s/it]
Validating: 0it [00:00, ?it/s]
Validating:   0% 0/1 [00:00<?, ?it/s]tcmalloc: large alloc 53440086016 bytes == 0x55b6abe98000 @  0x7f5e85ef9b6b 0x7f5e85f19379 0x7f5e2a0e326e 0x7f5e2a0e49e2 0x7f5e6d94eb49 0x7f5e6d94f897 0x7f5e6dd2bd89 0x7f5e6e4c59f6 0x7f5e6d9397fb 0x7f5e6d93ac33 0x7f5e6d93bb0d 0x7f5e6dab5b0f 0x7f5e6e4e15c3 0x7f5e6e4e1672 0x7f5e6e3500ed 0x7f5e6e350261 0x7f5e6fb40a3a 0x7f5e6fb41065 0x7f5e6e77421e 0x7f5e80878a35 0x7f5e808794c6 0x55b4ce6eea94 0x55b4ce5d9252 0x55b4ce61e260 0x55b4ce61fb1f 0x55b4ce6c1a31 0x55b4ce649526 0x55b4ce5da65a 0x55b4ce64cf40 0x55b4ce647c35 0x55b4ce5dafec
^C
```

**Comment by markus-eberts** [comment]
Yes, your machine is probably out of RAM. Obviously the RAM consumption increases with the document length. You need to either increase your RAM or split the input documents into smaller chunks. As far as I see, you also trained the model with just 2 batches. In this case, the model may predict many wrong entity mentions (since it is not trained on enough samples), which can increase memory consumption (more pairs to consider for relation extraction and coreference resolution). Also, you could decrease the maximum number of mentions/mention pairs processed concurrently by setting inference.max_spans/inference.max_coref_pairs/inference.max_rel_pairs to a low number (this will however also decrease inference speed).

**Comment by kbrajwani** [comment]
Currently i am just thinking about training. If it will start  training i am going to increase the data. I will try to divide my document into smaller chunks.
Thanks for support
